name: Build code

on: push

jobs:
  build_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - id: install
        name: Install Dependencies
        run: yarn
      - id: build
        name: Build Dependencies
        run: yarn build
